import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('배지 시드 데이터 생성 시작...');

  // 기존 사용자 배지 데이터 삭제
  await prisma.userBadge.deleteMany();
  console.log('✅ 기존 사용자 배지 삭제 완료');

  // 기존 배지 데이터 삭제
  await prisma.badge.deleteMany();
  console.log('✅ 기존 배지 삭제 완료');

  // 배지 생성
  const badges = await prisma.badge.createMany({
    data: [
      // === 기본 배지 (BASIC) - 입문자용 ===
      {
        code: 'NEWBIE',
        name: '신입 모아러',
        description: '첫 모임 참여',
        icon: '🌟',
        category: 'BASIC',
        conditionType: 'PARTICIPATION_COUNT',
        conditionValue: 1,
        isActive: true,
      },
      {
        code: 'FIRST_FRIEND',
        name: '첫 친구',
        description: '첫 친구 추가',
        icon: '🤝',
        category: 'BASIC',
        conditionType: 'FRIEND_COUNT',
        conditionValue: 1,
        isActive: true,
      },
      {
        code: 'PROFILE_COMPLETE',
        name: '프로필 완성',
        description: '프로필 100% 작성',
        icon: '📝',
        category: 'BASIC',
        conditionType: 'PROFILE_COMPLETE',
        conditionValue: 100,
        isActive: true,
      },
      {
        code: 'FIRST_REVIEW',
        name: '첫 리뷰어',
        description: '첫 리뷰 작성',
        icon: '✍️',
        category: 'BASIC',
        conditionType: 'REVIEW_COUNT',
        conditionValue: 1,
        isActive: true,
      },
      {
        code: 'ATTENDANCE_KING',
        name: '출석왕',
        description: '참석률 95% 이상 (10회 이상 참여)',
        icon: '✅',
        category: 'BASIC',
        conditionType: 'ATTENDANCE_RATE',
        conditionValue: 95,
        isActive: true,
      },
      {
        code: 'TIME_KEEPER',
        name: '시간지킴이',
        description: '지각 0회 (10회 이상 참여)',
        icon: '⏰',
        category: 'BASIC',
        conditionType: 'NO_LATE',
        conditionValue: 0,
        isActive: true,
      },
      {
        code: 'CHATTY',
        name: '수다쟁이',
        description: '채팅 100개 이상',
        icon: '💬',
        category: 'BASIC',
        conditionType: 'CHAT_COUNT',
        conditionValue: 100,
        isActive: true,
      },
      {
        code: 'SOCIAL_MASTER',
        name: '소셜 마스터',
        description: '친구 10명 추가',
        icon: '👥',
        category: 'BASIC',
        conditionType: 'FRIEND_COUNT',
        conditionValue: 10,
        isActive: true,
      },
      {
        code: 'DILIGENT_PARTICIPANT',
        name: '성실한 참여자',
        description: '참석률 90% 이상 (10회 이상 참여)',
        icon: '⭐',
        category: 'BASIC',
        conditionType: 'ATTENDANCE_RATE',
        conditionValue: 90,
        isActive: true,
      },
      {
        code: 'PHOTO_LOVER',
        name: '사진작가',
        description: '사진 10장 업로드',
        icon: '📸',
        category: 'BASIC',
        conditionType: 'PHOTO_COUNT',
        conditionValue: 10,
        isActive: true,
      },
      {
        code: 'CATEGORY_EXPLORER',
        name: '카테고리 탐험가',
        description: '5개 이상 다른 카테고리 모임 참여',
        icon: '🗺️',
        category: 'BASIC',
        conditionType: 'CATEGORY_COUNT',
        conditionValue: 5,
        isActive: true,
      },
      {
        code: 'MORNING_PERSON',
        name: '아침형 인간',
        description: '오전 모임 10회 참여',
        icon: '🌅',
        category: 'BASIC',
        conditionType: 'MORNING_MEETING',
        conditionValue: 10,
        isActive: true,
      },
      {
        code: 'NIGHT_OWL',
        name: '올빼미',
        description: '저녁 모임 10회 참여',
        icon: '🦉',
        category: 'BASIC',
        conditionType: 'NIGHT_MEETING',
        conditionValue: 10,
        isActive: true,
      },
      {
        code: 'WEEKEND_WARRIOR',
        name: '주말 전사',
        description: '주말 모임 10회 참여',
        icon: '🎮',
        category: 'BASIC',
        conditionType: 'WEEKEND_MEETING',
        conditionValue: 10,
        isActive: true,
      },

      // === 호스트 배지 (HOST) - 주최자용 ===
      {
        code: 'FIRST_HOST',
        name: '첫 주최',
        description: '첫 모임 주최',
        icon: '🎯',
        category: 'HOST',
        conditionType: 'HOSTING_COUNT',
        conditionValue: 1,
        isActive: true,
      },
      {
        code: 'GATHERING_MAKER',
        name: '모임 메이커',
        description: '모임 5개 이상 주최',
        icon: '🎪',
        category: 'HOST',
        conditionType: 'HOSTING_COUNT',
        conditionValue: 5,
        isActive: true,
      },
      {
        code: 'GATHERING_LEADER',
        name: '모임 리더',
        description: '모임 10개 이상 주최',
        icon: '👑',
        category: 'HOST',
        conditionType: 'HOSTING_COUNT',
        conditionValue: 10,
        isActive: true,
      },
      {
        code: 'GATHERING_MASTER',
        name: '모임 마스터',
        description: '모임 30개 이상 주최',
        icon: '🏆',
        category: 'HOST',
        conditionType: 'HOSTING_COUNT',
        conditionValue: 30,
        isActive: true,
      },
      {
        code: 'GATHERING_LEGEND',
        name: '모임 레전드',
        description: '모임 50개 이상 주최',
        icon: '👑',
        category: 'HOST',
        conditionType: 'HOSTING_COUNT',
        conditionValue: 50,
        isActive: true,
      },
      {
        code: 'POPULAR_HOST',
        name: '인기 호스트',
        description: '주최한 모임 평균 평점 4.5 이상',
        icon: '⭐',
        category: 'HOST',
        conditionType: 'HOST_RATING',
        conditionValue: 45,
        isActive: true,
      },
      {
        code: 'PERFECT_HOST',
        name: '완벽한 호스트',
        description: '주최한 모임 평균 평점 4.8 이상',
        icon: '💎',
        category: 'HOST',
        conditionType: 'HOST_RATING',
        conditionValue: 48,
        isActive: true,
      },
      {
        code: 'MEGA_HOST',
        name: '메가 호스트',
        description: '총 참여자 100명 이상 모집',
        icon: '🎊',
        category: 'HOST',
        conditionType: 'TOTAL_PARTICIPANTS',
        conditionValue: 100,
        isActive: true,
      },
      {
        code: 'RECURRING_HOST',
        name: '정기 호스트',
        description: '정기 모임 5개 이상 운영',
        icon: '🔄',
        category: 'HOST',
        conditionType: 'RECURRING_MEETING',
        conditionValue: 5,
        isActive: true,
      },
      {
        code: 'FAST_HOST',
        name: '신속 호스트',
        description: '모임 생성 후 24시간 내 마감 5회',
        icon: '⚡',
        category: 'HOST',
        conditionType: 'FAST_FILL',
        conditionValue: 5,
        isActive: true,
      },
      {
        code: 'LARGE_GROUP_HOST',
        name: '대규모 호스트',
        description: '30명 이상 모임 주최',
        icon: '🏟️',
        category: 'HOST',
        conditionType: 'LARGE_GROUP',
        conditionValue: 30,
        isActive: true,
      },
      {
        code: 'DIVERSE_HOST',
        name: '다재다능 호스트',
        description: '5개 이상 다른 카테고리 모임 주최',
        icon: '🎨',
        category: 'HOST',
        conditionType: 'HOST_CATEGORY_COUNT',
        conditionValue: 5,
        isActive: true,
      },

      // === 특별 배지 (SPECIAL) - 성취 기반 ===
      {
        code: 'REVIEW_STARTER',
        name: '리뷰 작성가',
        description: '리뷰 10개 작성',
        icon: '✍️',
        category: 'SPECIAL',
        conditionType: 'REVIEW_COUNT',
        conditionValue: 10,
        isActive: true,
      },
      {
        code: 'REVIEW_KING',
        name: '리뷰왕',
        description: '리뷰 50개 작성',
        icon: '📝',
        category: 'SPECIAL',
        conditionType: 'REVIEW_COUNT',
        conditionValue: 50,
        isActive: true,
      },
      {
        code: 'REVIEW_MASTER',
        name: '리뷰 마스터',
        description: '리뷰 100개 작성',
        icon: '📚',
        category: 'SPECIAL',
        conditionType: 'REVIEW_COUNT',
        conditionValue: 100,
        isActive: true,
      },
      {
        code: 'REVIEW_LEGEND',
        name: '리뷰 레전드',
        description: '리뷰 200개 작성',
        icon: '📖',
        category: 'SPECIAL',
        conditionType: 'REVIEW_COUNT',
        conditionValue: 200,
        isActive: true,
      },
      {
        code: 'HELPFUL_REVIEWER',
        name: '도움되는 리뷰어',
        description: '리뷰 좋아요 50개 받기',
        icon: '👍',
        category: 'SPECIAL',
        conditionType: 'REVIEW_LIKE',
        conditionValue: 50,
        isActive: true,
      },
      {
        code: 'FINISHER',
        name: '완주자',
        description: '챌린지 5개 완료',
        icon: '🎯',
        category: 'SPECIAL',
        conditionType: 'CHALLENGE_COUNT',
        conditionValue: 5,
        isActive: true,
      },
      {
        code: 'CHALLENGE_MASTER',
        name: '챌린지 마스터',
        description: '챌린지 10개 완료',
        icon: '🏅',
        category: 'SPECIAL',
        conditionType: 'CHALLENGE_COUNT',
        conditionValue: 10,
        isActive: true,
      },
      {
        code: 'ACTIVE_PARTICIPANT',
        name: '열정 참여자',
        description: '모임 10개 참여',
        icon: '🔥',
        category: 'SPECIAL',
        conditionType: 'PARTICIPATION_COUNT',
        conditionValue: 10,
        isActive: true,
      },
      {
        code: 'DEDICATED_PARTICIPANT',
        name: '헌신적 참여자',
        description: '모임 30개 참여',
        icon: '💫',
        category: 'SPECIAL',
        conditionType: 'PARTICIPATION_COUNT',
        conditionValue: 30,
        isActive: true,
      },
      {
        code: 'VETERAN_PARTICIPANT',
        name: '베테랑 참여자',
        description: '모임 50개 참여',
        icon: '💪',
        category: 'SPECIAL',
        conditionType: 'PARTICIPATION_COUNT',
        conditionValue: 50,
        isActive: true,
      },
      {
        code: 'LEGEND_PARTICIPANT',
        name: '전설 참여자',
        description: '모임 100개 참여',
        icon: '🌠',
        category: 'SPECIAL',
        conditionType: 'PARTICIPATION_COUNT',
        conditionValue: 100,
        isActive: true,
      },
      {
        code: 'HIGHLY_RATED',
        name: '인기쟁이',
        description: '평균 평점 4.5점 이상 (10회 이상 평가)',
        icon: '❤️',
        category: 'SPECIAL',
        conditionType: 'RATING_SCORE',
        conditionValue: 45,
        isActive: true,
      },
      {
        code: 'PERFECT_PERSON',
        name: '완벽한 사람',
        description: '평균 평점 4.8점 이상 (10회 이상 평가)',
        icon: '💎',
        category: 'SPECIAL',
        conditionType: 'RATING_SCORE',
        conditionValue: 48,
        isActive: true,
      },
      {
        code: 'WEEK_STREAK',
        name: '일주일 연속',
        description: '7일 연속 출석',
        icon: '📅',
        category: 'SPECIAL',
        conditionType: 'STREAK_DAYS',
        conditionValue: 7,
        isActive: true,
      },
      {
        code: 'TWO_WEEK_STREAK',
        name: '2주 연속',
        description: '14일 연속 출석',
        icon: '📆',
        category: 'SPECIAL',
        conditionType: 'STREAK_DAYS',
        conditionValue: 14,
        isActive: true,
      },
      {
        code: 'MONTH_STREAK',
        name: '한 달 연속',
        description: '30일 연속 출석',
        icon: '🔥',
        category: 'SPECIAL',
        conditionType: 'STREAK_DAYS',
        conditionValue: 30,
        isActive: true,
      },
      {
        code: 'HUNDRED_DAY_STREAK',
        name: '백일 연속',
        description: '100일 연속 출석',
        icon: '💯',
        category: 'SPECIAL',
        conditionType: 'STREAK_DAYS',
        conditionValue: 100,
        isActive: true,
      },
      {
        code: 'YEAR_STREAK',
        name: '1년 연속',
        description: '365일 연속 출석',
        icon: '🎆',
        category: 'SPECIAL',
        conditionType: 'STREAK_DAYS',
        conditionValue: 365,
        isActive: true,
      },
      {
        code: 'SOCIAL_KING',
        name: '사교왕',
        description: '친구 100명 이상',
        icon: '🎉',
        category: 'SPECIAL',
        conditionType: 'FRIEND_COUNT',
        conditionValue: 100,
        isActive: true,
      },
      {
        code: 'INFLUENCER',
        name: '인플루언서',
        description: '팔로워 50명 이상',
        icon: '🌟',
        category: 'SPECIAL',
        conditionType: 'FOLLOWER_COUNT',
        conditionValue: 50,
        isActive: true,
      },
      {
        code: 'MEGA_INFLUENCER',
        name: '메가 인플루언서',
        description: '팔로워 200명 이상',
        icon: '💫',
        category: 'SPECIAL',
        conditionType: 'FOLLOWER_COUNT',
        conditionValue: 200,
        isActive: true,
      },
      {
        code: 'GENEROUS_INVITER',
        name: '초대왕',
        description: '친구 20명 초대',
        icon: '🎁',
        category: 'SPECIAL',
        conditionType: 'INVITE_COUNT',
        conditionValue: 20,
        isActive: true,
      },
      {
        code: 'SUPER_INVITER',
        name: '슈퍼 초대왕',
        description: '친구 50명 초대',
        icon: '🎪',
        category: 'SPECIAL',
        conditionType: 'INVITE_COUNT',
        conditionValue: 50,
        isActive: true,
      },
      {
        code: 'POINT_COLLECTOR',
        name: '포인트 수집가',
        description: '1,000 포인트 획득',
        icon: '💰',
        category: 'SPECIAL',
        conditionType: 'POINT_EARN',
        conditionValue: 1000,
        isActive: true,
      },
      {
        code: 'POINT_MASTER',
        name: '포인트 마스터',
        description: '10,000 포인트 획득',
        icon: '💎',
        category: 'SPECIAL',
        conditionType: 'POINT_EARN',
        conditionValue: 10000,
        isActive: true,
      },
      {
        code: 'LEVEL_5',
        name: '레벨 5 달성',
        description: '레벨 5 달성',
        icon: '5️⃣',
        category: 'SPECIAL',
        conditionType: 'LEVEL',
        conditionValue: 5,
        isActive: true,
      },
      {
        code: 'LEVEL_10',
        name: '레벨 10 달성',
        description: '레벨 10 달성',
        icon: '🔟',
        category: 'SPECIAL',
        conditionType: 'LEVEL',
        conditionValue: 10,
        isActive: true,
      },
      {
        code: 'LEVEL_20',
        name: '레벨 20 달성',
        description: '레벨 20 달성',
        icon: '🎖️',
        category: 'SPECIAL',
        conditionType: 'LEVEL',
        conditionValue: 20,
        isActive: true,
      },
      {
        code: 'LEVEL_30',
        name: '레벨 30 달성',
        description: '레벨 30 달성',
        icon: '🏅',
        category: 'SPECIAL',
        conditionType: 'LEVEL',
        conditionValue: 30,
        isActive: true,
      },
      {
        code: 'EARLY_ADOPTER',
        name: '얼리어답터',
        description: '베타 기간 중 가입',
        icon: '🚀',
        category: 'SPECIAL',
        conditionType: 'EARLY_USER',
        conditionValue: 1,
        isActive: true,
      },
      {
        code: 'COMMUNITY_HELPER',
        name: '커뮤니티 도우미',
        description: '질문 답변 10회',
        icon: '🤓',
        category: 'SPECIAL',
        conditionType: 'ANSWER_COUNT',
        conditionValue: 10,
        isActive: true,
      },
      {
        code: 'SUPER_HELPER',
        name: '슈퍼 도우미',
        description: '질문 답변 50회',
        icon: '🦸',
        category: 'SPECIAL',
        conditionType: 'ANSWER_COUNT',
        conditionValue: 50,
        isActive: true,
      },
      {
        code: 'BOOKMARK_COLLECTOR',
        name: '북마크 수집가',
        description: '북마크 20개 저장',
        icon: '🔖',
        category: 'SPECIAL',
        conditionType: 'BOOKMARK_COUNT',
        conditionValue: 20,
        isActive: true,
      },
      {
        code: 'CONTENT_CREATOR',
        name: '콘텐츠 크리에이터',
        description: '게시물 50개 작성',
        icon: '✨',
        category: 'SPECIAL',
        conditionType: 'POST_COUNT',
        conditionValue: 50,
        isActive: true,
      },
      {
        code: 'SUPER_CREATOR',
        name: '슈퍼 크리에이터',
        description: '게시물 100개 작성',
        icon: '🎬',
        category: 'SPECIAL',
        conditionType: 'POST_COUNT',
        conditionValue: 100,
        isActive: true,
      },
      {
        code: 'COMMENT_MASTER',
        name: '댓글왕',
        description: '댓글 100개 작성',
        icon: '💭',
        category: 'SPECIAL',
        conditionType: 'COMMENT_COUNT',
        conditionValue: 100,
        isActive: true,
      },
      {
        code: 'SUPER_COMMENTER',
        name: '슈퍼 댓글러',
        description: '댓글 500개 작성',
        icon: '💬',
        category: 'SPECIAL',
        conditionType: 'COMMENT_COUNT',
        conditionValue: 500,
        isActive: true,
      },

      // === 시즌 배지 (SEASONAL) - 기간 한정 ===
      {
        code: 'FOUNDER',
        name: '창립 멤버',
        description: '초기 10명 가입자',
        icon: '🌈',
        category: 'SEASONAL',
        conditionType: 'EARLY_USER',
        conditionValue: 10,
        isActive: true,
      },
      {
        code: 'EARLY_BIRD',
        name: '얼리버드',
        description: '초기 100명 가입자',
        icon: '🦄',
        category: 'SEASONAL',
        conditionType: 'EARLY_USER',
        conditionValue: 100,
        isActive: true,
      },
      {
        code: 'PIONEER',
        name: '개척자',
        description: '초기 500명 가입자',
        icon: '🏕️',
        category: 'SEASONAL',
        conditionType: 'EARLY_USER',
        conditionValue: 500,
        isActive: true,
      },
      {
        code: 'SPRING_BLOSSOMER',
        name: '봄 꽃송이',
        description: '봄 시즌 5개 모임 참여',
        icon: '🌸',
        category: 'SEASONAL',
        conditionType: 'SEASON_PARTICIPATION',
        conditionValue: 5,
        isActive: false,
      },
      {
        code: 'SPRING_MASTER',
        name: '봄 마스터',
        description: '봄 시즌 10개 모임 참여',
        icon: '🌺',
        category: 'SEASONAL',
        conditionType: 'SEASON_PARTICIPATION',
        conditionValue: 10,
        isActive: false,
      },
      {
        code: 'SUMMER_LOVER',
        name: '여름 모임러',
        description: '여름 시즌 5개 모임 참여',
        icon: '☀️',
        category: 'SEASONAL',
        conditionType: 'SEASON_PARTICIPATION',
        conditionValue: 5,
        isActive: false,
      },
      {
        code: 'SUMMER_MASTER',
        name: '여름 마스터',
        description: '여름 시즌 10개 모임 참여',
        icon: '🏖️',
        category: 'SEASONAL',
        conditionType: 'SEASON_PARTICIPATION',
        conditionValue: 10,
        isActive: false,
      },
      {
        code: 'AUTUMN_LEAF',
        name: '가을 단풍',
        description: '가을 시즌 5개 모임 참여',
        icon: '🍂',
        category: 'SEASONAL',
        conditionType: 'SEASON_PARTICIPATION',
        conditionValue: 5,
        isActive: false,
      },
      {
        code: 'AUTUMN_MASTER',
        name: '가을 마스터',
        description: '가을 시즌 10개 모임 참여',
        icon: '🍁',
        category: 'SEASONAL',
        conditionType: 'SEASON_PARTICIPATION',
        conditionValue: 10,
        isActive: false,
      },
      {
        code: 'WINTER_WARRIOR',
        name: '겨울 전사',
        description: '겨울 시즌 5개 모임 참여',
        icon: '❄️',
        category: 'SEASONAL',
        conditionType: 'SEASON_PARTICIPATION',
        conditionValue: 5,
        isActive: false,
      },
      {
        code: 'WINTER_MASTER',
        name: '겨울 마스터',
        description: '겨울 시즌 10개 모임 참여',
        icon: '⛄',
        category: 'SEASONAL',
        conditionType: 'SEASON_PARTICIPATION',
        conditionValue: 10,
        isActive: false,
      },
      {
        code: 'NEW_YEAR_2025',
        name: '2025 새해 멤버',
        description: '2025년 1월 가입',
        icon: '🎊',
        category: 'SEASONAL',
        conditionType: 'JOIN_MONTH',
        conditionValue: 202501,
        isActive: false,
      },
      {
        code: 'LUNAR_NEW_YEAR_2025',
        name: '2025 설날 이벤트',
        description: '설날 이벤트 참여',
        icon: '🏮',
        category: 'SEASONAL',
        conditionType: 'EVENT_PARTICIPATION',
        conditionValue: 1,
        isActive: false,
      },
      {
        code: 'CHUSEOK_2025',
        name: '2025 추석 이벤트',
        description: '추석 이벤트 참여',
        icon: '🌕',
        category: 'SEASONAL',
        conditionType: 'EVENT_PARTICIPATION',
        conditionValue: 1,
        isActive: false,
      },
      {
        code: 'CHRISTMAS_2024',
        name: '2024 크리스마스',
        description: '크리스마스 이벤트 참여',
        icon: '🎄',
        category: 'SEASONAL',
        conditionType: 'EVENT_PARTICIPATION',
        conditionValue: 1,
        isActive: false,
      },
      {
        code: 'HALLOWEEN_2024',
        name: '2024 할로윈',
        description: '할로윈 이벤트 참여',
        icon: '🎃',
        category: 'SEASONAL',
        conditionType: 'EVENT_PARTICIPATION',
        conditionValue: 1,
        isActive: false,
      },
      {
        code: 'ANNIVERSARY_1',
        name: '1주년 기념',
        description: '1주년 이벤트 참여',
        icon: '🎂',
        category: 'SEASONAL',
        conditionType: 'EVENT_PARTICIPATION',
        conditionValue: 1,
        isActive: false,
      },
      {
        code: 'CHERRY_BLOSSOM_2025',
        name: '2025 벚꽃 축제',
        description: '벚꽃 축제 이벤트 참여',
        icon: '🌸',
        category: 'SEASONAL',
        conditionType: 'EVENT_PARTICIPATION',
        conditionValue: 1,
        isActive: false,
      },
    ],
  });

  console.log(`✅ ${badges.count}개의 배지 생성 완료`);

  // asdf@asdf.com 사용자 찾기
  const user = await prisma.user.findUnique({
    where: { email: 'asdf@asdf.com' },
  });

  if (!user) {
    console.error('❌ asdf@asdf.com 사용자를 찾을 수 없습니다.');
    return;
  }

  console.log(`✅ 사용자 찾음: ${user.email} (${user.id})`);

  // 배지 조회 (처음 8개)
  const allBadges = await prisma.badge.findMany({
    take: 8,
    orderBy: { createdAt: 'asc' },
  });

  // 사용자에게 배지 부여
  const userBadges = await prisma.userBadge.createMany({
    data: allBadges.map((badge, index) => ({
      userId: user.id,
      badgeId: badge.id,
      earnedAt: new Date(Date.now() - (8 - index) * 24 * 60 * 60 * 1000), // 마지막 8일 동안 하나씩
    })),
  });

  console.log(`✅ ${userBadges.count}개의 배지를 사용자에게 부여 완료`);

  // 결과 확인
  const userBadgeCount = await prisma.userBadge.count({
    where: { userId: user.id },
  });

  console.log('\n📊 최종 결과:');
  console.log(`   - 생성된 배지: ${badges.count}개`);
  console.log(`   - 사용자(${user.email})가 획득한 배지: ${userBadgeCount}개`);
  console.log('\n✨ 배지 시드 완료!\n');
}

main()
  .catch((e) => {
    console.error('오류 발생:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
